### ISSUE TITLE
ores are overwriten in a destrictive way

### ISSUE THREAD

**Issue by Skamiz** [CowboyLva/ebiomes#3]
As far as I can tell you are re-registering the ore 1 to 1 as they are defined in MTG. I realize that it's probably necessary for some reason involving biome and decoration IDs, but the way you go about it makes your mod incompatible with with most other mods which add ores themselves.

The proper way to go about it is to first make a copy of 'minetest.registered_ores' and then re-register the ores from the copy. That way you don't just delete all ores from mods which loaded before yours.

Same applies to decorations and biomes. Instead of registering them completely anew, make a copy of the previous definitions.
Then, while re-registreing them you can do something like:
if deco_def.name = "default:blueberry_bush" then
        deco_def.biomes = {"grassland"}
end

**Comment by CowboyLva** [comment]
Kinda new at this, but I'll give this a try when I can.

**Comment by CowboyLva** [comment]
Removed the needless unregistering of biomes and ores.
For now it unregisters and reregisters only decorations.
Technically I have fixed thing with ores so I can close this.

But if a mod adds custom caves there still can be problems. 
Will research things, but since ores solved - issue closed.
Thanks.
