### ISSUE TITLE
Nether and depth

### ISSUE THREAD

**Issue by adikalon** [CowboyLva/ebiomes#8]
The nether mod from PilzAdam breaks when launched with extra biomes. The problem is in the depth of biomes, which are located right up to level -31000 (there is simply nowhere to place nether). could you add a setting for maximum biome depth? Sorry for my English

**Comment by CowboyLva** [comment]
I have reviewed and merged your pull request which limits Extra Biomes underground biomes to y - 400.
Technically it means that below -400 ebiomes things stop even when no nether mod is installed, but it's fine since they are generic there is little to no difference dealt with this change.
Many thanks.
